-- Add market column if not exists
ALTER TABLE orders ADD COLUMN IF NOT EXISTS market VARCHAR(10) NOT NULL DEFAULT 'DE';

-- Update status check constraint to include all statuses
ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_status_check;
ALTER TABLE orders ADD CONSTRAINT orders_status_check CHECK (
  status IN (
    'INIT',
    'LOCAL_INITIALIZED',
    'FACTORY_ORDER_SUBMITTED',
    'ORDER_INITIALIZE_SUCCEED',
    'ORDER_INITIALIZE_FAILED',
    'PURCHASE_REQUEST_ACCEPTING',
    'PURCHASE_REQUEST_ACCEPTED',
    'PURCHASE_REQUEST_ACCEPT_FAILED',
    'CDOA_ACCEPTING',
    'CDOA_ACCEPTED',
    'CDOA_ACCEPT_FAILED'
  )
);
