package com.example.statemachine.domain.enums

enum class OrderStatus {
    INIT,
    LOCAL_INITIALIZED,
    FACTORY_ORDER_SUBMITTED,
    ORDER_INITIALIZE_SUCCEED,
    ORDER_INITIALIZE_FAILED,
    PURCHASE_REQUEST_ACCEPTING,
    PURCHASE_REQUEST_ACCEPTED,
    PURCHASE_REQUEST_ACCEPT_FAILED,
    CDOA_ACCEPTING,
    CDOA_ACCEPTED,
    CDOA_ACCEPT_FAILED,
}
